---
title: "git_01"
author: "Roxan Barakat"
date: "Spring semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
Inscribed to a Dear Child:  
In Memory of Golden Summer Hours  
And Whispers of a Summer Sea  

Girt with a boyish garb for boyish task,  
Eager she wields her spade: yet loves as well  
Rest on a friendly knee, intent to ask  
The tale he loves to tell.  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
I am silver and exact. I have no preconceptions.  
Whatever I see I swallow immediately  
Just as it is, unmisted by love or dislike.  
I am not cruel, only truthful‚  
The eye of a little god, four-cornered.  
Most of the time I meditate on the opposite wall.  
It is pink, with speckles. I have looked at it so long  
I think it is part of my heart. But it flickers.  
Faces and darkness separate us over and over.  
  